// <auto-generated />
using System;
using Eventhub.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Eventhub.Infra.Migrations
{
    [DbContext(typeof(EventhubDbContext))]
    [Migration("20251212020729_AddColumnNomeLocal")]
    partial class AddColumnNomeLocal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Eventhub.Domain.Entities.Acompanhantes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdParticipante")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("IdParticipante");

                    b.ToTable("Acompanhantes", (string)null);
                });

            modelBuilder.Entity("Eventhub.Domain.Entities.ComentarioFoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdFoto")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdFoto");

                    b.HasIndex("IdUsuario");

                    b.ToTable("ComentarioFoto", (string)null);
                });

            modelBuilder.Entity("Eventhub.Domain.Entities.ContribuicaoPresente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("FormaPagamento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("IdParticipante")
                        .HasColumnType("int");

                    b.Property<int>("IdPresente")
                        .HasColumnType("int");

                    b.Property<string>("LinkProduto")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("StatusContribuicaoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdParticipante");

                    b.HasIndex("IdPresente");

                    b.HasIndex("StatusContribuicaoId");

                    b.ToTable("ContribuicaoPresente", (string)null);
                });

            modelBuilder.Entity("Eventhub.Domain.Entities.Convite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdFoto")
                        .HasColumnType("int");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Nome2")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("TemaConvite")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("IdFoto");

                    b.ToTable("Convite", (string)null);
                });

            modelBuilder.Entity("Eventhub.Domain.Entities.CurtidaFoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdFoto")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("IdFoto", "IdUsuario")
                        .IsUnique();

                    b.ToTable("CurtidaFoto", (string)null);
                });

            modelBuilder.Entity("Eventhub.Domain.Entities.EnderecoEvento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("NomeLocal")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("PontoReferencia")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.ToTable("EnderecoEvento", (string)null);
                });

            modelBuilder.Entity("Eventhub.Domain.Entities.EnvioConvite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdConvite")
                        .HasColumnType("int");

                    b.Property<int>("IdEvento")
                        .HasColumnType("int");

                    b.Property<int>("IdParticipante")
                        .HasColumnType("int");

                    b.Property<int?>("IdStatusEnvioConvite")
                        .HasColumnType("int");

                    b.Property<string>("MensagemResposta")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("QtdAcompanhantes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdConvite");

                    b.HasIndex("IdEvento");

                    b.HasIndex("IdParticipante");

                    b.HasIndex("IdStatusEnvioConvite");

                    b.ToTable("EnvioConvite", (string)null);
                });

            modelBuilder.Entity("Eventhub.Domain.Entities.Evento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("IdEndereco")
                        .HasColumnType("int");

                    b.Property<int>("IdStatus")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoEvento")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuarioCriador")
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.Property<int>("MaxConvidado")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("IdEndereco");

                    b.HasIndex("IdStatus");

                    b.HasIndex("IdTipoEvento");

                    b.HasIndex("IdUsuarioCriador");

                    b.ToTable("Evento", (string)null);
                });

            modelBuilder.Entity("Eventhub.Domain.Entities.Fotos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Base64")
                        .IsRequired()
                        .HasColumnType("LONGTEXT");

                    b.Property<DateTime>("DataUpload")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("TamanhoKB")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Fotos", (string)null);
                });

            modelBuilder.Entity("Eventhub.Domain.Entities.Galeria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdEvento")
                        .HasColumnType("int");

                    b.Property<int>("IdFoto")
                        .HasColumnType("int");

                    b.Property<string>("Legenda")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("Ordem")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("Galeria");

                    b.Property<string>("Visibilidade")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("IdEvento");

                    b.HasIndex("IdFoto");

                    b.ToTable("Galeria", (string)null);
                });

            modelBuilder.Entity("Eventhub.Domain.Entities.Modulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Icone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<string>("Rota")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Modulo", (string)null);
                });

            modelBuilder.Entity("Eventhub.Domain.Entities.Notificacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataLeitura")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Icone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("IdEvento")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuarioDestino")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuarioOrigem")
                        .HasColumnType("int");

                    b.Property<string>("LinkAcao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("NotificacaoTipoId")
                        .HasColumnType("int");

                    b.Property<int>("Prioridade")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("IdEvento");

                    b.HasIndex("IdUsuarioDestino");

                    b.HasIndex("IdUsuarioOrigem");

                    b.HasIndex("NotificacaoTipoId");

                    b.ToTable("Notificacao", (string)null);
                });

            modelBuilder.Entity("Eventhub.Domain.Entities.NotificacaoTipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("FotosId")
                        .HasColumnType("int");

                    b.Property<string>("IconePadrao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TextoPadrao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("FotosId");

                    b.ToTable("NotificacaoTipo", (string)null);
                });

            modelBuilder.Entity("Eventhub.Domain.Entities.Participante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CadastroPendente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdEvento")
                        .HasColumnType("int");

                    b.Property<int>("IdPerfil")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdPerfil");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("IdEvento", "IdUsuario", "IdPerfil")
                        .IsUnique();

                    b.ToTable("Participante", (string)null);
                });

            modelBuilder.Entity("Eventhub.Domain.Entities.Perfil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasDefaultValue("A");

                    b.HasKey("Id");

                    b.ToTable("Perfil", (string)null);
                });

            modelBuilder.Entity("Eventhub.Domain.Entities.PerfilPermissao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdPerfil")
                        .HasColumnType("int");

                    b.Property<int>("IdPermissao")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdPermissao");

                    b.HasIndex("IdPerfil", "IdPermissao")
                        .IsUnique();

                    b.ToTable("PerfilPermissao", (string)null);
                });

            modelBuilder.Entity("Eventhub.Domain.Entities.Permissao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Chave")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("IdModulo")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Chave")
                        .IsUnique();

                    b.HasIndex("IdModulo");

                    b.ToTable("Permissao", (string)null);
                });

            modelBuilder.Entity("Eventhub.Domain.Entities.Presente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("IdEvento")
                        .HasColumnType("int");

                    b.Property<int>("IdFoto")
                        .HasColumnType("int");

                    b.Property<int>("IdStatus")
                        .HasColumnType("int");

                    b.Property<string>("LinkProduto")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdEvento");

                    b.HasIndex("IdFoto");

                    b.HasIndex("IdStatus");

                    b.ToTable("Presente", (string)null);
                });

            modelBuilder.Entity("Eventhub.Domain.Entities.ProgramacaoEvento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<TimeSpan>("Duracao")
                        .HasColumnType("time(6)");

                    b.Property<int>("IdEvento")
                        .HasColumnType("int");

                    b.Property<int>("IdFoto")
                        .HasColumnType("int");

                    b.Property<int>("IdStatus")
                        .HasColumnType("int");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Responsavel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("IdEvento");

                    b.HasIndex("IdFoto");

                    b.HasIndex("IdStatus");

                    b.ToTable("ProgramacaoEvento", (string)null);
                });

            modelBuilder.Entity("Eventhub.Domain.Entities.ResponsavelProgramacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Funcao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("IdProgramacao")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdProgramacao");

                    b.HasIndex("IdUsuario");

                    b.ToTable("ResponsavelProgramacao", (string)null);
                });

            modelBuilder.Entity("Eventhub.Domain.Entities.StatusContribuicao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("StatusContribuicao", (string)null);
                });

            modelBuilder.Entity("Eventhub.Domain.Entities.StatusEnvioConvite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("StatusEnvioConvite", (string)null);
                });

            modelBuilder.Entity("Eventhub.Domain.Entities.StatusEvento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("StatusEvento", (string)null);
                });

            modelBuilder.Entity("Eventhub.Domain.Entities.StatusPresente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("StatusPresente", (string)null);
                });

            modelBuilder.Entity("Eventhub.Domain.Entities.StatusProgramacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("StatusProgramacao", (string)null);
                });

            modelBuilder.Entity("Eventhub.Domain.Entities.TipoEvento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("IdFoto")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("IdFoto");

                    b.ToTable("TipoEvento", (string)null);
                });

            modelBuilder.Entity("Eventhub.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("IdFoto")
                        .HasColumnType("int");

                    b.Property<string>("KeycloakId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("IdFoto");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("Eventhub.Domain.Entities.UsuarioPerfilEvento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdEvento")
                        .HasColumnType("int");

                    b.Property<int>("IdPerfil")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdPerfil");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("IdEvento", "IdUsuario", "IdPerfil")
                        .IsUnique();

                    b.ToTable("UsuarioPerfilEvento", (string)null);
                });

            modelBuilder.Entity("Eventhub.Domain.Entities.UsuarioPermissao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Concedida")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("IdPermissao")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdPermissao");

                    b.HasIndex("IdUsuario", "IdPermissao")
                        .IsUnique();

                    b.ToTable("UsuarioPermissao", (string)null);
                });

            modelBuilder.Entity("Eventhub.Domain.Entities.Acompanhantes", b =>
                {
                    b.HasOne("Eventhub.Domain.Entities.Participante", "Participante")
                        .WithMany("Acompanhantes")
                        .HasForeignKey("IdParticipante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Participante");
                });

            modelBuilder.Entity("Eventhub.Domain.Entities.ComentarioFoto", b =>
                {
                    b.HasOne("Eventhub.Domain.Entities.Fotos", "Foto")
                        .WithMany("Comentarios")
                        .HasForeignKey("IdFoto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eventhub.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Comentarios")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Foto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Eventhub.Domain.Entities.ContribuicaoPresente", b =>
                {
                    b.HasOne("Eventhub.Domain.Entities.Participante", "Participante")
                        .WithMany("Contribuicoes")
                        .HasForeignKey("IdParticipante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eventhub.Domain.Entities.Presente", "Presente")
                        .WithMany("Contribuicoes")
                        .HasForeignKey("IdPresente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eventhub.Domain.Entities.StatusContribuicao", null)
                        .WithMany("Contribuicoes")
                        .HasForeignKey("StatusContribuicaoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Participante");

                    b.Navigation("Presente");
                });

            modelBuilder.Entity("Eventhub.Domain.Entities.Convite", b =>
                {
                    b.HasOne("Eventhub.Domain.Entities.Fotos", "Foto")
                        .WithMany("Convites")
                        .HasForeignKey("IdFoto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Foto");
                });

            modelBuilder.Entity("Eventhub.Domain.Entities.CurtidaFoto", b =>
                {
                    b.HasOne("Eventhub.Domain.Entities.Fotos", "Foto")
                        .WithMany("Curtidas")
                        .HasForeignKey("IdFoto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eventhub.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Curtidas")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Foto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Eventhub.Domain.Entities.EnvioConvite", b =>
                {
                    b.HasOne("Eventhub.Domain.Entities.Convite", "Convite")
                        .WithMany("EnviosConvite")
                        .HasForeignKey("IdConvite")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eventhub.Domain.Entities.Evento", "Evento")
                        .WithMany("EnviosConvite")
                        .HasForeignKey("IdEvento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eventhub.Domain.Entities.Participante", "Participante")
                        .WithMany("EnviosConvite")
                        .HasForeignKey("IdParticipante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eventhub.Domain.Entities.StatusEnvioConvite", "StatusEnvioConvite")
                        .WithMany()
                        .HasForeignKey("IdStatusEnvioConvite")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Convite");

                    b.Navigation("Evento");

                    b.Navigation("Participante");

                    b.Navigation("StatusEnvioConvite");
                });

            modelBuilder.Entity("Eventhub.Domain.Entities.Evento", b =>
                {
                    b.HasOne("Eventhub.Domain.Entities.EnderecoEvento", "Endereco")
                        .WithMany("Eventos")
                        .HasForeignKey("IdEndereco")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Eventhub.Domain.Entities.StatusEvento", "Status")
                        .WithMany("Eventos")
                        .HasForeignKey("IdStatus")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Eventhub.Domain.Entities.TipoEvento", "TipoEvento")
                        .WithMany("Eventos")
                        .HasForeignKey("IdTipoEvento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Eventhub.Domain.Entities.Usuario", "UsuarioCriador")
                        .WithMany("Eventos")
                        .HasForeignKey("IdUsuarioCriador")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Endereco");

                    b.Navigation("Status");

                    b.Navigation("TipoEvento");

                    b.Navigation("UsuarioCriador");
                });

            modelBuilder.Entity("Eventhub.Domain.Entities.Galeria", b =>
                {
                    b.HasOne("Eventhub.Domain.Entities.Evento", "Evento")
                        .WithMany("Galerias")
                        .HasForeignKey("IdEvento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eventhub.Domain.Entities.Fotos", "Foto")
                        .WithMany("Galerias")
                        .HasForeignKey("IdFoto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evento");

                    b.Navigation("Foto");
                });

            modelBuilder.Entity("Eventhub.Domain.Entities.Notificacao", b =>
                {
                    b.HasOne("Eventhub.Domain.Entities.Evento", "Evento")
                        .WithMany("Notificacoes")
                        .HasForeignKey("IdEvento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eventhub.Domain.Entities.Usuario", "UsuarioDestino")
                        .WithMany("NotificacoesRecebidas")
                        .HasForeignKey("IdUsuarioDestino")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Eventhub.Domain.Entities.Usuario", "UsuarioOrigem")
                        .WithMany("NotificacoesEnviadas")
                        .HasForeignKey("IdUsuarioOrigem")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Eventhub.Domain.Entities.NotificacaoTipo", null)
                        .WithMany("Notificacoes")
                        .HasForeignKey("NotificacaoTipoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Evento");

                    b.Navigation("UsuarioDestino");

                    b.Navigation("UsuarioOrigem");
                });

            modelBuilder.Entity("Eventhub.Domain.Entities.NotificacaoTipo", b =>
                {
                    b.HasOne("Eventhub.Domain.Entities.Fotos", null)
                        .WithMany("NotificacaoTipos")
                        .HasForeignKey("FotosId");
                });

            modelBuilder.Entity("Eventhub.Domain.Entities.Participante", b =>
                {
                    b.HasOne("Eventhub.Domain.Entities.Evento", "Evento")
                        .WithMany("Participantes")
                        .HasForeignKey("IdEvento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eventhub.Domain.Entities.Perfil", "Perfil")
                        .WithMany("Participantes")
                        .HasForeignKey("IdPerfil")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Eventhub.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Participantes")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Evento");

                    b.Navigation("Perfil");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Eventhub.Domain.Entities.PerfilPermissao", b =>
                {
                    b.HasOne("Eventhub.Domain.Entities.Perfil", "Perfil")
                        .WithMany("PerfilPermissoes")
                        .HasForeignKey("IdPerfil")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eventhub.Domain.Entities.Permissao", "Permissao")
                        .WithMany("PerfilPermissoes")
                        .HasForeignKey("IdPermissao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perfil");

                    b.Navigation("Permissao");
                });

            modelBuilder.Entity("Eventhub.Domain.Entities.Permissao", b =>
                {
                    b.HasOne("Eventhub.Domain.Entities.Modulo", "Modulo")
                        .WithMany("Permissoes")
                        .HasForeignKey("IdModulo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modulo");
                });

            modelBuilder.Entity("Eventhub.Domain.Entities.Presente", b =>
                {
                    b.HasOne("Eventhub.Domain.Entities.Evento", "Evento")
                        .WithMany()
                        .HasForeignKey("IdEvento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eventhub.Domain.Entities.Fotos", "Foto")
                        .WithMany()
                        .HasForeignKey("IdFoto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Eventhub.Domain.Entities.StatusPresente", "Status")
                        .WithMany("Presentes")
                        .HasForeignKey("IdStatus")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Evento");

                    b.Navigation("Foto");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Eventhub.Domain.Entities.ProgramacaoEvento", b =>
                {
                    b.HasOne("Eventhub.Domain.Entities.Evento", "Evento")
                        .WithMany("Programacoes")
                        .HasForeignKey("IdEvento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eventhub.Domain.Entities.Fotos", "Foto")
                        .WithMany("Programacoes")
                        .HasForeignKey("IdFoto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Eventhub.Domain.Entities.StatusProgramacao", "Status")
                        .WithMany("Programacoes")
                        .HasForeignKey("IdStatus")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Evento");

                    b.Navigation("Foto");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Eventhub.Domain.Entities.ResponsavelProgramacao", b =>
                {
                    b.HasOne("Eventhub.Domain.Entities.ProgramacaoEvento", "Programacao")
                        .WithMany("Responsaveis")
                        .HasForeignKey("IdProgramacao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eventhub.Domain.Entities.Usuario", "Usuario")
                        .WithMany("ResponsaveisProgramacao")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Programacao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Eventhub.Domain.Entities.TipoEvento", b =>
                {
                    b.HasOne("Eventhub.Domain.Entities.Fotos", "Foto")
                        .WithMany("TipoEventos")
                        .HasForeignKey("IdFoto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Foto");
                });

            modelBuilder.Entity("Eventhub.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("Eventhub.Domain.Entities.Fotos", "Foto")
                        .WithMany()
                        .HasForeignKey("IdFoto")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Foto");
                });

            modelBuilder.Entity("Eventhub.Domain.Entities.UsuarioPerfilEvento", b =>
                {
                    b.HasOne("Eventhub.Domain.Entities.Evento", "Evento")
                        .WithMany("UsuarioPerfis")
                        .HasForeignKey("IdEvento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eventhub.Domain.Entities.Perfil", "Perfil")
                        .WithMany("UsuarioPerfis")
                        .HasForeignKey("IdPerfil")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eventhub.Domain.Entities.Usuario", "Usuario")
                        .WithMany("UsuarioPerfis")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evento");

                    b.Navigation("Perfil");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Eventhub.Domain.Entities.UsuarioPermissao", b =>
                {
                    b.HasOne("Eventhub.Domain.Entities.Permissao", "Permissao")
                        .WithMany("UsuarioPermissoes")
                        .HasForeignKey("IdPermissao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eventhub.Domain.Entities.Usuario", "Usuario")
                        .WithMany("UsuarioPermissoes")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permissao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Eventhub.Domain.Entities.Convite", b =>
                {
                    b.Navigation("EnviosConvite");
                });

            modelBuilder.Entity("Eventhub.Domain.Entities.EnderecoEvento", b =>
                {
                    b.Navigation("Eventos");
                });

            modelBuilder.Entity("Eventhub.Domain.Entities.Evento", b =>
                {
                    b.Navigation("EnviosConvite");

                    b.Navigation("Galerias");

                    b.Navigation("Notificacoes");

                    b.Navigation("Participantes");

                    b.Navigation("Programacoes");

                    b.Navigation("UsuarioPerfis");
                });

            modelBuilder.Entity("Eventhub.Domain.Entities.Fotos", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("Convites");

                    b.Navigation("Curtidas");

                    b.Navigation("Galerias");

                    b.Navigation("NotificacaoTipos");

                    b.Navigation("Programacoes");

                    b.Navigation("TipoEventos");
                });

            modelBuilder.Entity("Eventhub.Domain.Entities.Modulo", b =>
                {
                    b.Navigation("Permissoes");
                });

            modelBuilder.Entity("Eventhub.Domain.Entities.NotificacaoTipo", b =>
                {
                    b.Navigation("Notificacoes");
                });

            modelBuilder.Entity("Eventhub.Domain.Entities.Participante", b =>
                {
                    b.Navigation("Acompanhantes");

                    b.Navigation("Contribuicoes");

                    b.Navigation("EnviosConvite");
                });

            modelBuilder.Entity("Eventhub.Domain.Entities.Perfil", b =>
                {
                    b.Navigation("Participantes");

                    b.Navigation("PerfilPermissoes");

                    b.Navigation("UsuarioPerfis");
                });

            modelBuilder.Entity("Eventhub.Domain.Entities.Permissao", b =>
                {
                    b.Navigation("PerfilPermissoes");

                    b.Navigation("UsuarioPermissoes");
                });

            modelBuilder.Entity("Eventhub.Domain.Entities.Presente", b =>
                {
                    b.Navigation("Contribuicoes");
                });

            modelBuilder.Entity("Eventhub.Domain.Entities.ProgramacaoEvento", b =>
                {
                    b.Navigation("Responsaveis");
                });

            modelBuilder.Entity("Eventhub.Domain.Entities.StatusContribuicao", b =>
                {
                    b.Navigation("Contribuicoes");
                });

            modelBuilder.Entity("Eventhub.Domain.Entities.StatusEvento", b =>
                {
                    b.Navigation("Eventos");
                });

            modelBuilder.Entity("Eventhub.Domain.Entities.StatusPresente", b =>
                {
                    b.Navigation("Presentes");
                });

            modelBuilder.Entity("Eventhub.Domain.Entities.StatusProgramacao", b =>
                {
                    b.Navigation("Programacoes");
                });

            modelBuilder.Entity("Eventhub.Domain.Entities.TipoEvento", b =>
                {
                    b.Navigation("Eventos");
                });

            modelBuilder.Entity("Eventhub.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("Curtidas");

                    b.Navigation("Eventos");

                    b.Navigation("NotificacoesEnviadas");

                    b.Navigation("NotificacoesRecebidas");

                    b.Navigation("Participantes");

                    b.Navigation("ResponsaveisProgramacao");

                    b.Navigation("UsuarioPerfis");

                    b.Navigation("UsuarioPermissoes");
                });
#pragma warning restore 612, 618
        }
    }
}
